interface AIInsightsProps {
  bullets: string[] | null;
}

export default function AIInsights({ bullets }: AIInsightsProps) {
  if (!bullets || bullets.length === 0) {
    return (
      <div
        style={{
          color: "var(--text-muted)",
          fontSize: "13px",
          textAlign: "center",
          padding: "24px 0",
        }}
      >
        No insights generated yet. Click Generate insights to analyse this report.
      </div>
    );
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
      {bullets.map((bullet, idx) => {
        const isLast = idx === bullets.length - 1;
        return (
          <div
            key={idx}
            style={{
              display: "flex",
              gap: "12px",
              paddingBottom: "12px",
              marginBottom: isLast ? 0 : "12px",
              borderBottom: isLast ? "none" : "0.5px solid var(--border-subtle)",
            }}
          >
            <div
              style={{
                width: "6px",
                height: "6px",
                borderRadius: "50%",
                backgroundColor: "#f59e0b",
                flexShrink: 0,
                marginTop: "6px",
              }}
            />
            <div
              style={{
                fontSize: "13px",
                color: "var(--text-secondary)",
                lineHeight: 1.6,
              }}
            >
              {bullet}
            </div>
          </div>
        );
      })}
      <div
        style={{
          fontSize: "11px",
          color: "var(--text-faint)",
          marginTop: "12px",
        }}
      >
        Generated by Gemini 1.5 Flash
      </div>
    </div>
  );
}
