"use client";

import Link from "next/link";

export default function TermsPage() {
  return (
    <div
      style={{
        backgroundColor: "#0a0a0a",
        color: "#f2f2f0",
        minHeight: "100vh",
        fontFamily: "system-ui, -apple-system, sans-serif",
        padding: "48px 24px",
        display: "flex",
        justifyContent: "center",
      }}
    >
      <div
        style={{
          maxWidth: "680px",
          width: "100%",
        }}
      >
        <Link
          href="/"
          style={{
            color: "#d98a5f",
            fontSize: "13px",
            textDecoration: "none",
            fontWeight: 500,
            display: "inline-block",
            marginBottom: "32px",
          }}
        >
          &larr; Back to home
        </Link>

        <h1
          style={{
            fontFamily: "Georgia, serif",
            fontSize: "36px",
            color: "#f2f2f0",
            marginBottom: "8px",
          }}
        >
          Terms of Service
        </h1>

        <p
          style={{
            fontSize: "13px",
            color: "rgba(255,255,255,0.4)",
            marginBottom: "40px",
          }}
        >
          Last updated: February 2026
        </p>

        <div
          style={{
            backgroundColor: "#111111",
            border: "0.5px solid rgba(255,255,255,0.08)",
            borderRadius: "12px",
            padding: "32px",
            display: "flex",
            flexDirection: "column",
            gap: "24px",
            fontSize: "14px",
            color: "rgba(255,255,255,0.7)",
            lineHeight: 1.6,
          }}
        >
          <section>
            <h2
              style={{
                fontSize: "16px",
                fontWeight: 500,
                color: "#f2f2f0",
                marginBottom: "8px",
              }}
            >
              1. Project Disclaimer
            </h2>
            <p style={{ margin: 0 }}>
              Forkast is a developer side-project provided free of charge. It is provided &ldquo;as is&rdquo; without warranties or guarantees of uptime or commercial performance.
            </p>
          </section>

          <section>
            <h2
              style={{
                fontSize: "16px",
                fontWeight: 500,
                color: "#f2f2f0",
                marginBottom: "8px",
              }}
            >
              2. Analytical Insights
            </h2>
            <p style={{ margin: 0 }}>
              All recommendations, metrics, and menu insights generated by Forkast are intended strictly for decision support. Restaurant owners should verify operational changes against their own business parameters.
            </p>
          </section>

          <section>
            <h2
              style={{
                fontSize: "16px",
                fontWeight: 500,
                color: "#f2f2f0",
                marginBottom: "8px",
              }}
            >
              3. Acceptable Use
            </h2>
            <p style={{ margin: 0 }}>
              Users agree not to upload malicious files or attempt to exploit the service endpoints. Accounts found misusing the service may be suspended.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
